### ISSUE TITLE
Pagination/Grouping for long "Article Index" results

### ISSUE THREAD

**Issue by panoptical** [codex-press/app#7] opened 2016-10-28 08:30 UTC
For pages like the LGBTQ Crisis News Feed that display a large number of articles, can we get some way of chunking these results so the user gets less of an information blast?  For instance, pagination (user sees 6-8 articles, then clicks a link to "older"), or load-on-demand (user sees 6-8, then when the user scrolls down the next 6-8 load)?  Or a link to an Archive page which is sortable by date, or has a calendar view, or some other way of organizing these stories?

**Comment by twfarnam** [comment] 2016-10-28 14:27
I'm not sure I see the benefit of paginating the index. We would just be making the reader click something for no reason. What am I missing?

Currently all the indexes in Coda are sorted by date. What other way is there to sort them besides date?

**Comment by panoptical** [comment] 2016-10-28 16:54
Well I think the issue is that if there are like 40 news stories and we list them all on one page we giving visitors too much information at once.  I don't know the metrics on this but it seems like a pretty standard website feature to group results in chunks rather than an endless stream (c.f. Google search results).

**Comment by panoptical** [comment] 2016-10-28 16:56
Also about sorting - I imagine we'll eventually want to be able to sort or filter based on the conceptual categories that Natalia envisioned for Coda - so, by region, edition, and current.  Maybe also by author or story type.

**Comment by twfarnam** [comment] 2016-10-28 17:52
I don't believe having a click to reveal more articles helps the reader absorb the list. The reason you see this on other web sites probably has more to do with limitations of their software or a desire to push more page views and advertising impressions. I'm closing this as "wontfix". Besides, it's something you guys can implement in Javascript if you believe there's a UX benefit.

As far as sorting/filtering that sounds like duplicate of the search feature which is definitely on the roadmap.

**Closed by twfarnam** 2016-10-28 17:52 UTC
Labels: duplicate, enhancement, wontfix
